
name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: codemerx/assembly-differ-action@v0.2.6
      with:
        args: '-h'

