
name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: codemerx/test-assembly-differ-action
        path: test-assembly-differ-action
    - uses: actions/checkout@v2
      with:
        repository: codemerx/assembly-differ-action
        path: assembly-differ-action
    - uses: codemerx/assembly-differ-action@v0.3.2
      with:
        args: '"assembly|${{github.workspace}}\test-assembly-differ-action\assembly-differ.dll" "assembly|${{github.workspace}}\test-assembly-differ-action\assembly-differ.dll"'
        assembly-differ-binaries: '${{github.workspace}}\assembly-differ-action\binaries'

