
name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: codemerx/test-assembly-differ-action
    - uses: actions/checkout@v2
      with:
        repository: codemerx/assembly-differ-action
    - uses: codemerx/assembly-differ-action@v0.3.1
      with:
        args: '"assembly|${{github.workspace}}\assembly-differ.dll" "assembly|${{github.workspace}}\assembly-differ.dll"'

