
name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      repository: codemerx/test-assembly-differ-action
    - uses: codemerx/assembly-differ-action@v0.3.1
      with:
        args: '"assembly|D:\a\test-assembly-differ-action\test-assembly-differ-action\test-assembly-differ-action\assembly-differ.dll" "assembly|D:\a\test-assembly-differ-action\test-assembly-differ-action\test-assembly-differ-action\assembly-differ.dll"'

