
name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: codemerx/test-assembly-differ-action
        path: test-assembly-differ-action
    - uses: codemerx/assembly-differ-action@v0.3.5
      with:
        args: '"assembly|${{github.workspace}}\test-assembly-differ-action\latest-release\TestLibrary.dll" "assembly|${{github.workspace}}\test-assembly-differ-action\TestLibrary\TestLibrary\bin\debug\netstandard2.0\TestLibrary.dll" -p=major'

