name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: codemerx/assembly-differ-action@release-preparation
      with:
        args: '"assembly|${{github.workspace}}\latest-release\TestLibrary.dll" "assembly|${{github.workspace}}\TestLibrary\TestLibrary\bin\debug\netstandard2.0\TestLibrary.dll" -p=major'

