
name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: codemerx/assembly-differ-action@v0.3.0
      with:
        args: '"assembly|assembly-differ.dll" "assembly|assembly-differ.dll"'

